"""Generated-document storage.

Documents are written twice: into SQLite (so the UI can show them) and onto disk
in `data/documents` (so you can open, print, or attach them without the app
running). The agent and the UI both go through here, so a resume the agent
produced at 3am is indistinguishable from one you generated by hand.
"""

from __future__ import annotations

from typing import Any

from . import config, db

KINDS = ("resume", "cover_letter", "review", "interview_prep", "onboarding")


def save(job: dict[str, Any], kind: str, content: str) -> dict[str, Any]:
    cursor = db.execute(
        "INSERT INTO documents (job_id, kind, content, created_at) VALUES (?, ?, ?, ?)",
        (job["id"], kind, content, db.now()),
    )
    doc_id = int(cursor.lastrowid)

    config.ensure_dirs()
    filename = (
        f"{config.slugify(job['company'])}-{config.slugify(job['title'])}-{kind}-{doc_id}.md"
    )
    path = config.DOCS_DIR / filename
    path.write_text(content, encoding="utf-8")

    application = db.query_one("SELECT id FROM applications WHERE job_id = ?", (job["id"],))
    if application:
        db.add_event(application["id"], "document", f"Generated {kind.replace('_', ' ')}")

    return {
        "id": doc_id, "job_id": job["id"], "kind": kind, "content": content,
        "created_at": db.now(), "file": str(path),
    }


def review_to_markdown(review: dict[str, Any]) -> str:
    def bullets(items: list[str]) -> str:
        return "\n".join(f"- {item}" for item in items) or "- (none)"

    return (
        f"# Fit review — {review.get('verdict', 'unknown')} ({review.get('score', '?')}/100)\n\n"
        f"## Strengths\n{bullets(review.get('strengths', []))}\n\n"
        f"## Gaps\n{bullets(review.get('gaps', []))}\n\n"
        f"## Talking points\n{bullets(review.get('talking_points', []))}\n\n"
        f"## Resume advice\n{review.get('resume_advice', '')}\n"
    )
